### ISSUE TITLE
Failed to start browser with other os error

### ISSUE THREAD

**Issue by wenJanus** [mdn/headless-examples#4]
const binary = new firefox.Binary('C:/Program Files/Mozilla Firefox/firefox.exe');
        binary.addArguments('-headless');
        this.driver = new webdriver.Builder()
          .forBrowser('firefox')
          .setFirefoxOptions(new firefox.Options().setBinary(binary))
          .build();

(node:2628) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SessionNotCreatedError: Failed to start browser C:/Program Files/Mozilla Firefox/firefox.exe: other os error

**Comment by chrisdavidmills** [comment]
@mykmelez hi Myk - could you comment on this issue? Thanks in advance.

**Comment by mykmelez** [comment]
That error probably means that selenium-webdriver can't find the Firefox executable at the specified location. It works for me in my testing with this complete script:

```
const webdriver = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');

const binary = new firefox.Binary('C:/Program Files/Mozilla Firefox/firefox.exe');
binary.addArguments('-headless');
this.driver = new webdriver.Builder()
.forBrowser('firefox')
.setFirefoxOptions(new firefox.Options().setBinary(binary))
.build();
```

A couple things to check:
1. You've installed the release or beta version of Firefox rather than the Nightly version (which is at a different path: `C:/Program Files/Nightly/`).
2. If you're on 64-bit Windows, you've installed the 64-bit version of Firefox rather than the 32-bit version (which is at a different path: `C:/Program Files (x86)/Mozilla Firefox/`).
